fastlane_version "1.66.0"

default_platform :ios

import "./examples/Lisa_Fastfile"
import "./examples/Darius_Fastfile"

platform :ios do
  before_all do
  end

  after_all do |lane|
    if lane == :test_and_push
      push_to_git_remote
    elsif lane == :continuously_build
      slack
    end
  end

  error do |lane, exception|
  end
end