# Uncomment the lines below you want to change by removing the # in the beginning

# A list of devices you want to take the screenshots from
devices([
  "iPhone 6",
  "iPhone 6 Plus"
])

languages([
  "en-US",
  "es-ES"
])

# remove the '#' to clear all previously generated screenshots before creating new ones
clear_previous_screenshots true 
clean true
number_of_retries 2
reinstall_app true